### ISSUE TITLE
Many packages reference their build path ('C:/building/msys64'), not their install path 

### ISSUE THREAD

**Issue by emmenlau** [msys2/MINGW-packages#1670]
I have problems building an application that links vtk. Standard cmake tries to get libraries from `'C:/building/msys64'` that don't not exist on my machine. I've checked now a bit more broadly, and indeed there are hundreds of references to this build path. I've checked with:

```
grep -Irn 'C:/building/' /
```

and found literally hundreds of references. Here a few examples:

```
/mingw64/bin/curl-config:159:          echo ${exec_prefix}/lib/libcurl.a -LC:/building/msys64/mingw64/lib -pipe -LC:/building/msys64/mingw64/lib -LC:/building/msys64/mingw64/lib -lnghttp2 -lidn -lrtmp -lssh2 -lssl -lcrypto -lssl -lcrypto -lgdi32 -lwldap32 -lz -lws2_32
/mingw64/bin/cythonize2-script.py:1:#!C:/building/msys64/mingw64/bin/python2.exe
/mingw64/bin/freetype-config:144:  staticlibs="-lfreetype -L/mingw64/lib -lz -L/mingw64/lib -lbz2 -L/mingw64/lib -lpng16 -lz -L/mingw64/lib -LC:/building/msys64/mingw64/lib -L/mingw64/lib -lharfbuzz -lglib-2.0 -lintl -pthread -lws2_32 -lole32 -lwinmm -lshlwapi -lpcre -lintl -lpcre -lgraphite2"
/mingw64/bin/python-config.sh:43:prefix_build="C:/building/msys64/mingw64"
/mingw64/bin/python2-pyuic5.bat:1:@C:/building/msys64/mingw64/bin/python2.exe -m PyQt5.uic.pyuic %1 %2 %3 %4 %5 %6 %7 %8 %9
/mingw64/bin/python3-config:39:prefix_build="C:/building/msys64/mingw64"
/mingw64/bin/python3.5-config:39:prefix_build="C:/building/msys64/mingw64"
/mingw64/bin/python3.5m-config:39:prefix_build="C:/building/msys64/mingw64"
/mingw64/bin/xml2-config:89:            echo -lxml2 -LC:/building/msys64/mingw64/lib -lz -LC:/building/msys64/mingw64/lib -llzma   -liconv
/mingw64/bin/xml2-config:91:            echo -L${libdir} -lxml2 -LC:/building/msys64/mingw64/lib -lz -LC:/building/msys64/mingw64/lib -llzma   -liconv
/mingw64/bin/xml2-config:94:        echo -L${libdir} -lxml2 -LC:/building/msys64/mingw64/lib -lz -LC:/building/msys64/mingw64/lib -llzma   -liconv     -lws2_32
/mingw64/bin/xslt-config:92:the_libs="-L${libdir} -lxslt  -L/mingw64/lib -lxml2 -LC:/building/msys64/mingw64/lib -lz -LC:/building/msys64/mingw64/lib -llzma -liconv -lws2_32  "
/mingw64/include/vtk-6.3/vtkConfigure.h:132:#define VTK_CXX_COMPILER "C:/building/msys64/mingw64/bin/g++.exe"
/mingw64/lib/cmake/vtk-6.3/Modules/vtkCommonCore.cmake:4:set(vtkCommonCore_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkexpat.cmake:3:set(vtkexpat_LIBRARIES "C:/building/msys64/mingw64/lib/libexpat.dll.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkexpat.cmake:4:set(vtkexpat_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkfreetype.cmake:3:set(vtkfreetype_LIBRARIES "C:/building/msys64/mingw64/lib/libfreetype.dll.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkfreetype.cmake:4:set(vtkfreetype_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include/freetype2")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkGUISupportQt.cmake:9:set(VTK_QT_MOC_EXECUTABLE "C:/building/msys64/mingw64/bin/moc.exe")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkGUISupportQt.cmake:15:  set(Qt5Widgets_DIR "C:/building/msys64/mingw64/lib/cmake/Qt5Widgets")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkGUISupportQtOpenGL.cmake:11:  set(Qt5OpenGL_DIR "C:/building/msys64/mingw64/lib/cmake/Qt5OpenGL")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkGUISupportQtSQL.cmake:11:  set(Qt5Widgets_DIR "C:/building/msys64/mingw64/lib/cmake/Qt5Widgets")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkGUISupportQtSQL.cmake:16:  set(Qt5Sql_DIR "C:/building/msys64/mingw64/lib/cmake/Qt5Sql")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkGUISupportQtWebkit.cmake:11:  set(Qt5WebKitWidgets_DIR "C:/building/msys64/mingw64/lib/cmake/Qt5WebKitWidgets")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkhdf5.cmake:3:set(vtkhdf5_LIBRARIES "C:/building/msys64/mingw64/lib/libhdf5.dll.a;C:/building/msys64/mingw64/lib/libhdf5_hl.dll.a;C:/building/msys64/mingw64/lib/libhdf5.dll.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkhdf5.cmake:4:set(vtkhdf5_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkjpeg.cmake:3:set(vtkjpeg_LIBRARIES "C:/building/msys64/mingw64/lib/libjpeg.dll.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkjpeg.cmake:4:set(vtkjpeg_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkjsoncpp.cmake:3:set(vtkjsoncpp_LIBRARIES "C:/building/msys64/mingw64/lib/libjsoncpp.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkjsoncpp.cmake:4:set(vtkjsoncpp_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include")
/mingw64/lib/cmake/vtk-6.3/Modules/vtklibxml2.cmake:3:set(vtklibxml2_LIBRARIES "C:/building/msys64/mingw64/lib/libxml2.dll.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtklibxml2.cmake:4:set(vtklibxml2_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include/libxml2")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkoggtheora.cmake:3:set(vtkoggtheora_LIBRARIES "C:/building/msys64/mingw64/lib/libtheoraenc.dll.a;C:/building/msys64/mingw64/lib/libtheoradec.dll.a;C:/building/msys64/mingw64/lib/libogg.dll.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkoggtheora.cmake:4:set(vtkoggtheora_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include;C:/building/msys64/mingw64/include")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkpng.cmake:3:set(vtkpng_LIBRARIES "C:/building/msys64/mingw64/lib/libpng.dll.a;C:/building/msys64/mingw64/lib/libz.dll.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkpng.cmake:4:set(vtkpng_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include;C:/building/msys64/mingw64/include")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkPython.cmake:3:set(vtkPython_LIBRARIES "C:/building/msys64/mingw64/lib/libpython2.7.dll.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkPython.cmake:4:set(vtkPython_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include/python2.7")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkRenderingQt.cmake:10:  set(Qt5Widgets_DIR "C:/building/msys64/mingw64/lib/cmake/Qt5Widgets")
/mingw64/lib/cmake/vtk-6.3/Modules/vtktiff.cmake:3:set(vtktiff_LIBRARIES "C:/building/msys64/mingw64/lib/libtiff.dll.a")
/mingw64/lib/cmake/vtk-6.3/Modules/vtktiff.cmake:4:set(vtktiff_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkViewsQt.cmake:11:  set(Qt5Widgets_DIR "C:/building/msys64/mingw64/lib/cmake/Qt5Widgets")
/mingw64/lib/cmake/vtk-6.3/Modules/vtkWrappingTcl.cmake:4:set(vtkWrappingTcl_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3;C:/building/msys64/mingw64/include")
```

**Comment by DavidEGrayson** [comment]
This is a bad problem indeed.  I though that this part of makepkg (which I contributed to) is supposed to warn about references like that to alert the person building or developing the package:

https://github.com/Alexpux/MSYS2-pacman/blob/master/scripts/libmakepkg/lint_package/build_references.sh.in

**Comment by emmenlau** [comment]
Nice! So I guess that the original package uploader might have missed the warning? I'm currently fixing this manually with perl, but it would be great if the binary packages could be fixed... is this possible even without recompile? Some of them currently don't compile...

**Comment by DavidEGrayson** [comment]
The binary packages are just .tar.xz files so I suppose you could extract them, fix them, and repackage them.

**Comment by mati865** [comment]
I think that sed would be enough but there are 2 cases:

1. If paths can be relative reduce inside `PKGBUILD` them to look like that: `/mingw64/lib/`
2. If paths must be absoulte (it's bad itself because it breaks portability) add `.install` file and call sed inside the `post_install()`

**Comment by mati865** [comment]
@emmenlau 
Arch have patches to fix building https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/vtk6
It could be bumped to version 7 also.

**Comment by filnet** [comment]
vtk should be fixed soon.

**Comment by matham** [comment]
What's the process for releases? Because I notice pacman still serves the version of vtk that is not fixed. Could a updated version of vtk from master please be released? Because I ran into this exact same issue trying to get itk to build until I realized it's because of this.

**Comment by emmenlau** [comment]
Dear @matham the fix that was merged by @Alexpux https://github.com/Alexpux/MINGW-packages/pull/1818 has increased the pkgrel, so a new build should have been triggered. Its possible that at the time, vtk did not compile, and if it fails at first then AFAIK it will not be re-tried later.

**Comment by filnet** [comment]
My understanding of how msys2 works currently it that there is no automatic publishing of packages.
Everything is done manually Alexpux whenever he has time.

The last change (done by yours truly ;) ) to vtk was either overlooked or was not deemed important enough to warrant a build+publish.

**Comment by mati865** [comment]
Probably it couldn't build.

09.03.2017 17:07 "filnet" <notifications@github.com> napisał(a):

**Comment by matham** [comment]
Looking at #1818, I can see that the 32 bit build failed, but I think it may have just run out of time as the build probably took more than the allowed time: https://tea-ci.org/Alexpux/MINGW-packages/1595.

There is no error present, which suggests it was just a time issue and the CI just terminated the build. I was worried about that before actually as even on my fast computer some builds (itk) took around an hour.

**Comment by mati865** [comment]
CI isn't used to create release packages, it is too unstable, but it's great for testing PR's.

**Comment by dineshbkumar06** [comment]
Armadillo (mingw-w64-x86_64-armadillo-8.100.1-1-any) package currently has reference to C:/building/msys64/mingw64/include/ in the "/msys64/mingw64/include/armadillo_bits/config.hpp" file.

**Comment by lakinwecker** [comment]
glog and ceres also refer to C:/building

**Comment by eskrut** [comment]
Same problem at dlib package

**Comment by eskrut** [comment]
@peterbud , two files
mingw32/lib/cmake/dlib/dlib.cmake
```
-  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;C:/building/msys64/mingw32/include;C:/building/msys64/mingw32/include;C:/building/msys64/mingw32/include"
-  INTERFACE_LINK_LIBRARIES "ws2_32;winmm;comctl32;gdi32;imm32;C:/building/msys64/mingw32/lib/libgif.dll.a;C:/building/msys64/mingw32/lib/libpng.dll.a;C:/building/msys64/mingw32/lib/libz.dll.a;C:/building/msys64/mingw32/lib/libjpeg.dll.a;C:/building/msys64/mingw32/lib/libopenblas.dll.a;C:/building/msys64/mingw32/lib/liblapack.dll.a;C:/building/msys64/mingw32/lib/libsqlite3.dll.a;C:/building/msys64/mingw32/lib/libfftw3.dll.a"
+  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
+  INTERFACE_LINK_LIBRARIES "ws2_32;winmm;comctl32;gdi32;imm32;/mingw32/lib/libgif.dll.a;/mingw32/lib/libpng.dll.a;/mingw32/lib/libz.dll.a;/mingw32/lib/libjpeg.dll.a;/mingw32/lib/libopenblas.dll.a;/mingw32/lib/liblapack.dll.a;/mingw32/lib/libsqlite3.dll.a;/mingw32/lib/libfftw3.dll.a"
```
and
mingw32/lib/cmake/dlib/dlibConfig.cmake
```
-set(dlib_INCLUDE_DIRS "/mingw32/include" "C:/building/msys64/mingw32/include;C:/building/msys64/mingw32/include;C:/building/msys64/mingw32/include")
+set(dlib_INCLUDE_DIRS "/mingw32/include/")
```

**Comment by peterbud** [comment]
Thanks @eskrut .  I have submitted a PR: #4112 - in theory it should fix this.

**Comment by stahta01** [comment]
> Armadillo (mingw-w64-x86_64-armadillo-8.100.1-1-any) package currently has reference to C:/building/msys64/mingw64/include/ in the "/msys64/mingw64/include/armadillo_bits/config.hpp" file.

I hope this is fixed in #4758  Tim S.

**Comment by thehans** [comment]
Hello, I'm experiencing this same issue with the CGAL package.  

```
grep -r building/msys64
lib/cmake/CGAL/CGAL_CoreExports.cmake:  INTERFACE_INCLUDE_DIRECTORIES "C:/building/msys64/mingw64/include;C:/building/msys64/mingw64/include"
lib/cmake/CGAL/CGAL_CoreExports.cmake:  INTERFACE_LINK_LIBRARIES "C:/building/msys64/mingw64/lib/libgmp.dll.a;C:/building/msys64/mingw64/lib/libmpfr.a;CGAL::CGAL;Boost::thread"
lib/cmake/CGAL/CGAL_CoreExports.cmake:  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "C:/building/msys64/mingw64/include;C:/building/msys64/mingw64/include"
lib/cmake/CGAL/CGALExports.cmake:  INTERFACE_INCLUDE_DIRECTORIES "C:/building/msys64/mingw64/include;C:/building/msys64/mingw64/include;C:/building/msys64/mingw64/include;${_IMPORT_PREFIX}/include"
lib/cmake/CGAL/CGALExports.cmake:  INTERFACE_LINK_LIBRARIES "C:/building/msys64/mingw64/lib/libgmp.dll.a;C:/building/msys64/mingw64/lib/libmpfr.a"
lib/cmake/CGAL/CGALExports.cmake:  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "C:/building/msys64/mingw64/include;C:/building/msys64/mingw64/include;C:/building/msys64/mingw64/include"
lib/cmake/CGAL/CGAL_ImageIOExports.cmake:  INTERFACE_INCLUDE_DIRECTORIES "C:/building/msys64/mingw64/include"
lib/cmake/CGAL/CGAL_ImageIOExports.cmake:  INTERFACE_LINK_LIBRARIES "CGAL::CGAL;C:/building/msys64/mingw64/lib/libz.dll.a"
lib/cmake/CGAL/CGAL_ImageIOExports.cmake:  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "C:/building/msys64/mingw64/include"
```

**Comment by kernelplv** [comment]
Hello! 
`
mingw32-make.exe \[2\]: \*\*\* No rule to make target 'C:/building/msys64/mingw64/lib/libexpat.dll.a ', needed by ...
`

**Comment by lazka** [comment]
Since this quite old and it's unclear what issues remain I'm closing this. Please open issues for separate packages or provide PRs that fix the issues.
