### ISSUE TITLE
[texlive-extra-utils] PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)

### ISSUE THREAD

**Issue by ArrSeaJay** [msys2/MINGW-packages#19981]
### Description / Steps to reproduce the issue

try to run `latexmk`

### Expected behavior

No error message

### Actual behavior

PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
Currently blocked on #19921 since texlive fails to build.

**Comment by Biswa96** [comment]
Please ignore my previous question. It seems that the build error would happen without the patch file.

**Comment by reneparis** [comment]
Since https://github.com/msys2/MINGW-packages/issues/20510 was closed due to duplication, I'd like to know what the current status of this issue is, or if it is possible for me to help you out here:

> As far as I understand it, fmtutil.exe is the source. Maybe recompiling it with zlib 1.3.1 will help, but I'm not really into this.
If there is anything I can do to narrow the issue further down, let me know.

**Comment by MehdiChinoune** [comment]
texlive is unusable.
The issue is open for too long without any workaround.
There must be a decision whether fix it or drop it.

**Comment by jhol** [comment]
> texlive is unusable. The issue is open for too long without any workaround. There must be a decision whether fix it or drop it.

I'm greatly in need of a fix for this bug. I would be happy to put time into finding a solution, but it's not clear to me where to look.

**Comment by naveen521kk** [comment]
> texlive is unusable. The issue is open for too long without any workaround. There must be a decision whether fix it or drop it.

It's a rebuild provided we fix https://github.com/msys2/msys2-runtime/issues/208 or find a workaround for it.

**Comment by MehdiChinoune** [comment]
> > texlive is unusable. The issue is open for too long without any workaround. There must be a decision whether fix it or drop it.
> 
> It's simply a rebuild provided we fix [msys2/msys2-runtime#208](https://github.com/msys2/msys2-runtime/issues/208) or find a workaround for it.

I am aware of that, but I don't see any activity or attempt to fix the issue.
If it's not fixable or if the maintainers have not intention/time to fix it. So better to drop texlive.

**Comment by jhol** [comment]
@reneparis is offering these patches which, if I understand correctly, should fix the issue: https://github.com/msys2/msys2-runtime/issues/208#issuecomment-2126696647 , they just need review/approval.

**Comment by mmuetzel** [comment]
I started to look into rebuilding texlive-bin: #21290 
However, it is still failing for me locally (issue in ICU header?).

**Comment by MehdiChinoune** [comment]
Should be fixed now.
