### ISSUE TITLE
Recent x265 update (3.4-1) breaks ffmpeg (4.2.3-2)

### ISSUE THREAD

**Issue by Fsu0413** [msys2/MINGW-packages#6597]
I only tried x64 builds.
ffmpeg exits with code 127 on execution.
Even "ffmpeg --help" does not work.

Edit: I have downgraded x265 to 3.3-1 and ffmpeg works.

**Comment by lazka** [comment]
a ffmpeg update is on the way

**Comment by lazka** [comment]
should work now

**Comment by Fsu0413** [comment]
It works now. Thanks!

**Comment by sladecraven** [comment]
The issue is still there with ffmpeg 4.3.1-1 and x265 3.4.-1

**Comment by lazka** [comment]
I can't reproduce

**Comment by sladecraven** [comment]
STrange. Launching ffmpeg.exe produces a non resolve function in libx265 (ffmpeg 4.3.1-1 and x265 3.4.-1)

**Comment by sladecraven** [comment]
Entry point `x265_api_get_19` is not found in avcodec-58.dll.
Latest msys2 sync, versions ffmpeg 4.3.1-1 and x265 3.4.-1.
Any idea ?

**Comment by Biswa96** [comment]
Try to reinstall those packages with `pacman -S package_name`.
