### ISSUE TITLE
Cannot build a wheel with `pip install -U .` on MINGW

### ISSUE THREAD

**Issue by eine** [msys2/MINGW-packages#7262]
Coming from #7014.

> https://github.com/msys2/MINGW-packages/issues/7014#issuecomment-723819190
> * [eine/tox/actions/runs/353412467](https://github.com/eine/tox/actions/runs/353412467)
> * [eine/tox@42f2987](https://github.com/eine/tox/commit/42f2987c7f78371e6aabb1b0a9a72bdcee09df6e)

/cc @danyeaw

**Comment by danyeaw** [comment]
@eine I don't think this is related to tox, I think building a wheel of any package will fail with this error. We should fix this, but you should be able to also work around this by running `pip install tox`.

**Comment by lazka** [comment]
Looks like this is mainly setuptools_scm calling git, which returns unix paths?

**Comment by lazka** [comment]
setting SETUPTOOLS_SCM_PRETEND_VERSION to something bogus might help there

**Comment by eine** [comment]
@lazka, see https://github.com/eine/tox/runs/1401381763?check_suite_focus=true#step:4:25:

```
  C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-sg6__a_t/overlay/lib/python3.8/site-packages/setuptools/dist.py:466: UserWarning: The version specified ('something_bogus') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
    warnings.warn(
  error: [WinError 267] The directory name is invalid
  ----------------------------------------
ERROR: Command errored out with exit status 1: D:/a/_temp/msys/msys64/mingw64/bin/python.exe D:/a/_temp/msys/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py get_requires_for_build_wheel 'C:/Users/RUNNER~1/AppData/Local/Temp/tmphkar8j6i' Check the logs for full command output.
```

**Comment by lazka** [comment]
needs a proper Python package version I guess

**Comment by naveen521kk** [comment]
I think this is fixed no?

**Comment by eine** [comment]
@naveen521kk, still failing: https://github.com/eine/tox/runs/1783158220?check_suite_focus=true#step:4:59

```
...
   FileNotFoundError: [WinError 3] The system cannot find the path specified: '/c/Users/runneradmin/AppData/Local/Temp/pip-req-build-t75crwi9'
  ----------------------------------------
WARNING: Discarding file:///D://a/tox/tox. Command errored out with exit status 1: D:/a/_temp/msys/msys64/mingw64/bin/python.exe D:/a/_temp/msys/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py get_requires_for_build_wheel 'C:/Users/RUNNER~1/AppData/Local/Temp/tmpvnwdg9xz' Check the logs for full command output.
ERROR: Command errored out with exit status 1: D:/a/_temp/msys/msys64/mingw64/bin/python.exe D:/a/_temp/msys/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py get_requires_for_build_wheel 'C:/Users/RUNNER~1/AppData/Local/Temp/tmpvnwdg9xz' Check the logs for full command output.
Error: Process completed with exit code 1.
```

**Comment by naveen521kk** [comment]
Does it have a `pyproject.toml` for PEP517 build?
If yes that's the problem. It creates a venv for installing things, and it doesn't use the patched libraries which we have. Maybe try removing 
```toml
[build-system]
requires = [
    "setuptools >= 40.0.4",
    "setuptools_scm >= 2.0.0, <4",
    "wheel >= 0.29.0",
]
build-backend = 'setuptools.build_meta'
```
and ru `pip install -U .`?

**Comment by naveen521kk** [comment]
From #7825 things work locally.
```sh
$ pip install -U .
Defaulting to user installation because normal site-packages is not writeable
Processing h:/mingw/tox
    Preparing wheel metadata ... done
Requirement already satisfied: toml>=0.9.4 in c:/msys64/mingw64/lib/python3.8/site-packages (from tox==3.14.4.dev7+gb7a1559) (0.10.2)
Requirement already satisfied: virtualenv>=16.0.0 in c:/msys64/mingw64/lib/python3.8/site-packages (from tox==3.14.4.dev7+gb7a1559) (20.4.0)
Requirement already satisfied: py<2,>=1.4.17 in c:/msys64/mingw64/lib/python3.8/site-packages (from tox==3.14.4.dev7+gb7a1559) (1.10.0)
Requirement already satisfied: colorama>=0.4.1 in c:/msys64/mingw64/lib/python3.8/site-packages (from tox==3.14.4.dev7+gb7a1559) (0.4.4)
Requirement already satisfied: packaging>=14 in c:/msys64/mingw64/lib/python3.8/site-packages (from tox==3.14.4.dev7+gb7a1559) (20.8)
Requirement already satisfied: filelock<4,>=3.0.0 in c:/msys64/mingw64/lib/python3.8/site-packages (from tox==3.14.4.dev7+gb7a1559) (3.0.12)
Requirement already satisfied: pluggy<1,>=0.12.0 in c:/msys64/mingw64/lib/python3.8/site-packages (from tox==3.14.4.dev7+gb7a1559) (0.13.1)
Requirement already satisfied: six<2,>=1.0.0 in c:/msys64/mingw64/lib/python3.8/site-packages (from tox==3.14.4.dev7+gb7a1559) (1.15.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:/msys64/mingw64/lib/python3.8/site-packages (from packaging>=14->tox==3.14.4.dev7+gb7a1559) (2.4.7)
Requirement already satisfied: appdirs<2,>=1.4.3 in c:/msys64/mingw64/lib/python3.8/site-packages (from virtualenv>=16.0.0->tox==3.14.4.dev7+gb7a1559) (1.4.4)
Requirement already satisfied: distlib<1,>=0.3.1 in c:/msys64/mingw64/lib/python3.8/site-packages (from virtualenv>=16.0.0->tox==3.14.4.dev7+gb7a1559) (0.3.1)
Building wheels for collected packages: tox
  Building wheel for tox (PEP 517) ... done
  Created wheel for tox: filename=tox-3.14.4.dev7+gb7a1559-py2.py3-none-any.whl size=82132 sha256=9c50a7cfb1651aa43ef8fb5ba9a8b1491a3460796f6da53c1d3de46512495e8d
  Stored in directory: C:/Users/User/AppData/Local/Temp/pip-ephem-wheel-cache-h_zzc_q0/wheels/1f/13/13/c3b324f79faf2b7933f9e37c856b26e888bb59ea16f7bd1516
Successfully built tox
Installing collected packages: tox
  Attempting uninstall: tox
    Found existing installation: tox 3.14.4.dev7+gb7a1559
    Uninstalling tox-3.14.4.dev7+gb7a1559:
      Successfully uninstalled tox-3.14.4.dev7+gb7a1559
  WARNING: The scripts tox-quickstart.exe and tox.exe are installed in 'C:\Users\Naveen User/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed tox-3.14.4.dev7+gb7a1559
```

**Comment by eine** [comment]
@naveen521kk, after waiting some days for changes to be uploaded, I'm still getting the same result: https://github.com/eine/tox/actions/runs/530347778 Am I missing anything?

**Comment by naveen521kk** [comment]
@eine  Again, as I previously told pip creates a virtual environment and install things in that while building anything. In this case, `setuptools_scm` is patched in pacman repo but it isn't in upstream, so you have to disable that using
```sh
pip install  --no-build-isolation -U .
```

**Comment by eine** [comment]
@naveen521kk, these are the result with `--no-build-isolation`: https://github.com/eine/tox/actions/runs/530400296. I think that the relevant error is `ModuleNotFoundError: No module named 'tox.version'`, which is defined in `setup.py`: https://github.com/tox-dev/tox/blob/master/setup.py

**Comment by naveen521kk** [comment]
@eine did you install setuptools_scm from Pacman beforehand?

**Comment by eine** [comment]
No! I did it now: https://github.com/eine/tox/actions/runs/530456252

```
 WARNING: test command found but not installed in testenv
  cmd: D:/a/_temp/msys/msys64/mingw64/bin/python.EXE
  env: D:/a/tox/tox/.tox/.tox
Maybe you forgot to specify a dependency? See also the allowlist_externals envconfig setting.
...
Installing collected packages: tox
  Attempting uninstall: tox
    Found existing installation: tox 0.1.dev1+gb3bddd9.d20210202
    Uninstalling tox-0.1.dev1+gb3bddd9.d20210202:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'd:/a/_temp/msys/msys64/mingw64/bin/tox.exe'
Consider using the `--user` option or check the permissions.

ERROR: invocation failed (exit code 1)
ERROR: could not install deps [tox >= 3.12]; v = InvocationError("D:/a/_temp/msys/msys64/mingw64/bin/python.EXE -m pip install 'tox >= 3.12'", 1)
.tox finish: getenv D:/a/tox/tox/.tox/.tox after 2.53 seconds
.tox start: provision 
.tox finish: provision  after 0.00 seconds
```

It seems that installation is successful now but running tox itself is failing?

**Comment by naveen521kk** [comment]
I don't know sorry. Maybe tox is running but it tries to replace itself which isn't supported in Windows though.

**Comment by naveen521kk** [comment]
https://github.com/eine/tox/runs/1813793538?check_suite_focus=true#step:4:42 looks weird to me. Why does it have dependency on itself?

**Comment by eine** [comment]
The tests are executed on a fork of tox and try to execute tox's own testsuite, which uses tox for management. Each of the jobs is a different procedure for installing the deps and running `tox -rvv -e py36`. 

Tox, by default, tries to create isolated environments, installs the dependencies in there and executes the tests. Hence, I think it might be failing to setup that isolated environment (in this case a Python 3.6 one).

Anyway, I think this is a corner case, because typically tox will be used for testing any project other than itself. The local pip install seems to be working, which is what this issue was about.

**Comment by naveen521kk** [comment]
Maybe should we patch tox to pass that parameter always?
