### ISSUE TITLE
recent kicad requires dblatex

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#909]
[100%] Built target pcbnew
-- find_file( DBLATEX_COMMAND dblatex ): DBLATEX_COMMAND-NOTFOUND
-- Found PythonInterp: U:/msys64/mingw64/bin/python.exe (found version "2.7.10")
CMake Error at U:/msys64/mingw64/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find DBLATEX (missing: DBLATEX_COMMAND)
Call Stack (most recent call first):
  U:/msys64/mingw64/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindDBLATEX.cmake:84 (find_package_handle_standard_args)
  CMakeLists.txt:50 (find_package)

so close to the goal...

**Comment by slorquet** [comment]
Error is triggered by this cmakefile:
https://github.com/KiCad/kicad-doc/blob/master/CMakeLists.txt

**Comment by slorquet** [comment]
These guys are also playing with that
https://lists.launchpad.net/kicad-developers/msg17972.html

but FOP is not available in msys2 either.

**Comment by stahta01** [comment]
I have found a work around for this issue; but, I do NOT know KiCad well enough to test the work around.
Is anyone posted on the issue willing to test my patch to the mingw-w64-kicad-git package and test my new package of "mingw-w64-kicad4.0-doc"? I Plan on pushing my changes in about a week. I need to do more build testing and installing; but, once that is done I will need some to verify the help files work right.

Tim S.

**Comment by umarcor** [comment]
It seems that this issue was fixed but not closed?

**Comment by stahta01** [comment]
The issue was not really fixed; but, a work around was found to download the processed doc file and then package them.
